"""
Configuration settings for the Resume Analysis Service
"""

# --- GEMINI API RETRY CONFIGURATION ---
GEMINI_MAX_RETRIES = 5
GEMINI_RETRY_MIN_WAIT = 4  # seconds
GEMINI_RETRY_MAX_WAIT = 300  # seconds (5 minutes)
GEMINI_RETRY_MULTIPLIER = 2  # exponential backoff multiplier

# --- SERVICE LEVEL RETRY CONFIGURATION ---
SERVICE_MAX_RETRIES = 3
SERVICE_RETRY_DELAY = 60  # seconds between service-level retries

# --- FALLBACK ANALYSIS CONFIGURATION ---
FALLBACK_BASE_SCORE = 50
FALLBACK_OPTIMAL_RESUME_LENGTH_MIN = 1000
FALLBACK_OPTIMAL_RESUME_LENGTH_MAX = 3000
FALLBACK_FORMATTING_PENALTY_PER_ISSUE = 5
FALLBACK_MAX_FORMATTING_PENALTY = 20

# --- LOGGING CONFIGURATION ---
LOG_LEVEL = "INFO"
LOG_DETAILED_ERRORS = True
LOG_API_ATTEMPTS = True

# --- HEALTH CHECK CONFIGURATION ---
HEALTH_CHECK_INTERVAL = 300  # seconds (5 minutes)